### PR TITLE
feat: add many toArray methods

### PR DESCRIPTION
**Pull request by yjhmelody**

### CODE REVIEW

**Comment by MaxGraey** [comment]
Could you give me an actual example of what it's for? StringSink is just temporary object which optimize string concatenation. Ideally it should have minimal and transparent API

**Comment by yjhmelody** [comment]
- Sometime we need add prefix to the string at late stage or modified some char.
- Some character data may not be stored in string (for example, the encoding is different)

**Comment by yjhmelody** [comment]
It is okay not to provide these, but I think these internal fields should be exposed as @unsafe so that users can optimize based on the API

**Comment by MaxGraey** [comment]
> Sometime we need add prefix to the string at late stage or modified some char.

Wouldn't it be easier to do this right before concatenation? Otherwise you have to spend time searching the buffer as well, which is much less efficient

> Some character data may not be stored in string (for example, the encoding is different)

It's not very clear. What do you mean?

Can I take a real life case?

**Comment by yjhmelody** [comment]
Maybe what I said is not quite right. Many times we need to process strings like arrays, because it is more efficient, but AS seems to be troublesome at present, because it is UTF16 encoded, once I strictly require UTF8, the string type cannot be used or has more performance Overhead, and currently String.UTF8.encode returns an array like ArrayBuffer.

I don't have a very precise example. I try my best to give examples of problems that I will encounter (but I haven’t encountered them yet). For example, if I need to store data (basically ASCII or UTF8), then I will definitely not use UTF-16. Then after I get Array<u8>, For ASCII I will delete all even-numbered bytes.

I think I should close this PR, and I should implement a library that meets my needs by myself

**Comment by MaxGraey** [comment]
I don't want overcomplicate such simple library by adding to it a huge variety of methods that may never be needed in usual cases. In general, I would first accumulate experience and battle-tested feedback before adding anything else.
So thanks for your efforts but it's too early for adding this

**Comment by MaxGraey** [comment]
Could you create feature request issue before creating actual PR with new feature? (This does not apply to bug fixes)

**Comment by yjhmelody** [comment]
I closed it.

**Pull request closed without merging**
