### PR TITLE
feat: add writeUnsafe

### PR DESCRIPTION
**Pull request by yjhmelody**

### CODE REVIEW

**Comment by MaxGraey** [comment]
Sorry, but I don't understand why we need `writeUnsafe` especially due to it not significantly improve performance and only noises API

**Comment by yjhmelody** [comment]
Benchmark shows that performance can be improved by 1 times in extreme cases.
In many scenarios, the string size is predictable, and users can pre-allocate more space.
Maybe should I only export the `ensureCapacity`?

**Comment by MaxGraey** [comment]
> In many scenarios, the string size is predictable, and users can pre-allocate more space

So make public `ensureCapacity`  will be enough right? Could you just do this and remove all unnecessary extra benchmarks and other changes include `writeUnsafe`?

**Comment by yjhmelody** [comment]
I wrote another test, and I found that the two apis have a great impact on performance.
Please see this:
```
100 strings:
---------------
benchStringSinkAccum2: StringSink AS: 0.0055 ms
benchStringSinkAccumUnsafe2: tringSink AS Unsafe: 0.027 ms
50,000 strings:
---------------
benchStringSinkAccum2: StringSink AS: 0.78 ms
benchStringSinkAccumUnsafe2: tringSink AS Unsafe: 0.51 ms
200,000 strings:
---------------
benchStringSinkAccum2: StringSink AS: 3.43 ms
benchStringSinkAccumUnsafe2: tringSink AS Unsafe: 2.03 ms
Done in 37.20s.
```
They only differ in write method.

**Comment by yjhmelody** [comment]
To be honest, my library is very dependent on the performance limit of this library. Because it is related to smart contracts

**Comment by MaxGraey** [comment]
I created another API which has similar goals. Would you be satisfied with that?

**Pull request closed without merging**
